config/routes.rb
Rails.application.routes.draw do
  resources :books
  get 'homes/top'
  root to: 'homes#top'
  patch 'books/:id' => 'books#update', as: 'update_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
    flash[:new] = 'Book was successfully created.'
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end
  
  def show
    @show = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:update] = 'Book was successfully updated.'
    redirect_to book_path(@book.id) 
    else
    render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy 
    redirect_to '/books'  
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1 class="edit">Editing Book</h1>


<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this book from being saved:
<ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
</ul>
<% end %>


<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>
<div class="field">
  <h4>Title</h4>
  <%= f.text_field :title %>
</div>

<div class="field">
  <h4>Body</h4>
  <%= f.text_area :body %>
  </div>
  <div>
  <%= f.submit 'Update Book' %>
  </div>
<% end %>

<p><%= link_to "Show", book_path %> | <%= link_to "Back", books_path %></p>

app/views/books/index.html.erb
<p></p>
<h1 class="index-h1">Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |b| %>
    
    <tr>
    <td><%= b.title %></td>
    <td><%= b.body %></td>
    <td><%= link_to "Show", book_path(b.id) %></td>
    <td><%= link_to "Edit", edit_book_path(b.id) %></td>
    <td><%= link_to "Destroy", book_path(b.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>
    <% end %>
  </tbody>
</table>


<h2 class="new-books">New Books</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: Book.new do |f| %>

<div class="field">
<h4>Title</h4>
<%= f.text_field :title %>
</div>

<div class="field">
<h4>Body</h4>
<%= f.text_area :body %>
</div>
<%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<%= flash[:new] %>
<%= flash[:update] %>


<p><strong>Title:</strong> <%= @show.title %></p>

<p><strong>Body:</strong> <%= @show.body %></p>


<p><%= link_to "Edit", edit_book_path %> | <%= link_to "Back", books_path %></p>

app/views/homes/top.html.erb
<h1>
  ようこそ
  <strong>
    Bookers
  </strong>
  へ!
</h1>
<p>
  <strong>
    Bookers
  </strong>
  では、様々な書籍に関するあなたの意見や
</p>
<p>印象を共有し交換することができます</p>
<p>
  <a href="/books">start</a>
</p>

app/views/layouts/_error_messages.html.erb
<% if Book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% Book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>